<?php

namespace App\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

use App\Entity\Profile;
use App\Entity\ProfileImage;
use App\Form\EditProfileType;
use App\Form\ProfileImageType;


class EditProfileController extends AbstractController
{
    /**
    * @Route("/editprofile/{id}", name="editProfile_view")
    */
    public function updateProfile($id = "1", Request $request, SessionInterface $session)
    {
        $profile = $session->get('profile');
        $profileId = $profile->getId();

        // update Profile handle
        $profile = $this->getDoctrine()
            ->getRepository(Profile::class)
            ->find($id);
        
        $form = $this->createForm(EditProfileType::class, $profile);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            $userProfile = $form->getData();

            $profileName = $userProfile->getName();
            $profileEmail = $userProfile->getEmail();
            $profilePassword = $userProfile->getPassword();
            
            $entityManager = $this->getDoctrine()->getManager();

            $profile->setName($profileName);
            $profile->setEmail($profileEmail);
            $profile->setPassword($profilePassword);

            $session->set('profile', $profile);

            $entityManager->persist($profile);
            $entityManager->flush();

            return $this->redirectToRoute('discover_view');
        }

        // upload Image handle

        $profilesImage = $this->getDoctrine()
        ->getRepository(Profile::class)
        ->find($profileId);
        
        $profileImage = new ProfileImage();
        $Uploadform = $this->createForm(ProfileImageType::class, $profileImage);
        $Uploadform->handleRequest($request);

        $oldImages = $this->getDoctrine()
        ->getRepository(ProfileImage::class)
        ->findBy(array("profile_id"=>$id));

            if ($Uploadform->isSubmitted() && $Uploadform->isValid()) {

                $entityManager = $this->getDoctrine()->getManager();


                forEach($oldImages as $oldImage){
                    $oldImage->setActiveState(false);  
                }
                // $oldImages->setActiveState(false);

                /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
                // $file=$profileImage->getImagePath();
                $file=$Uploadform->get('image_path')->getData();

                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('profileImages_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $profileImage->setImagePath($fileName);

                $entityManager->persist($profileImage);
                $entityManager->flush();

                return $this->redirectToRoute('editProfile_view');
            }


            if ($request->isXmlHttpRequest()) {  
                $action = $_POST['action'];
                $imageId = $_POST['id'];

                $entityManager = $this->getDoctrine()->getManager();

                $otherImages = $entityManager->getRepository(ProfileImage::class)->findby(array('profile_id' => $profileId));
                $image = $entityManager->getRepository(ProfileImage::class)->find($imageId);
    
                if($action == "changeImage"){

                    forEach($otherImages as $otherImage){
                        $otherImage->setActiveState(false);  
                    }
                    $image->setActiveState(true);
                }
                $entityManager->flush();
                return true; 
             }

      $view = 'editProfile.html.twig';
        $model = array('form' => $form->createView(), 'Uploadform' => $Uploadform->createView(), 'profileImage' => $profileImage, 'oldImages' => $oldImages, 'profile' => $profile);

        return $this->render($view, $model);

    }

     /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
?>