<?php

namespace App\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;

use App\Entity\Profile;
use App\Entity\ProfileImage;
use App\Form\ProfileImageType;

class UploadImageController extends AbstractController
{
    /**
    * @Route("/editprofile/{id}", name="editProfile_view")
    */
    public function uploadAction($id= "1", Request $request)
    {

        $session = new Session();
        $session->start();

        $profileId=1;

        $profile = $this->getDoctrine()
        ->getRepository(Profile::class)
        ->find($profileId);

        $session->set('profile', $profile);

        //UNCOMMENT to let this page work with sessions
        //$profile = $session->get('profile');
        //$profileId = $profile->getId();
        
        $profileImage = new ProfileImage();
        $Uploadform = $this->createForm(ProfileImageType::class, $profileImage);
        $Uploadform->handleRequest($request);


            if ($Uploadform->isSubmitted() && $Uploadform->isValid()) {

                

                $entityManager = $this->getDoctrine()->getManager();

                /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
                // $file=$profileImage->getImagePath();
                $file=$Uploadform->get('image_path')->getData();

                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('profileImages_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $profileImage->setImagePath($fileName);

                $entityManager->persist($profileImage);
                $entityManager->flush();

                return $this->redirectToRoute('editProfile_view');
            }
       

        $view = 'editProfile.html.twig';
        $model = array('Uploadform' => $Uploadform->createView());
        return $this->render($view, $model);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


}
?>